### ISSUE TITLE
Strange value for calculated age

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#124]
Not sure if this is a Gramps bug, just posting it without investigating as I noticed it by accident:

`/api/people/?gramps_id=I0554&profile=all`

has this:

<img width="459" alt="grafik" src="https://user-images.githubusercontent.com/10965193/102129444-a23a4b80-3e4f-11eb-91bd-6d0832dd9dca.png">

The age at death is clearly wrong.

**Comment by cdhorn** [comment]
Looked at this quick and it is wrong in Gramps proper. Unsure if we should open something there and close this.

**Comment by DavidMStraub** [comment]
Cleaning up old issues, I looked into this in more detail and ... it's complicated. In any case, I don't think we should track it here as a bug.

The reason for the large maximum age of 110 years is the Gramps configuration parameter `behavior.date-about-range` that sets the &pm; delta for estimated dates; by default, it is set to 50 years, so the maximum age would be Jan 1, 1746 to Dec 12, 1855.

For the minimum age, it gets complicated because the "sort value" of the birth date is actually higher than the one of the death date and because the earliest death year is before the latest birth year. So the correct answer would be "0". But I will anyway close this and conclude with:

![grafik](https://imgs.xkcd.com/comics/datetime.png)
https://xkcd.com/2867/

**Comment by InblEric** [comment]
Thanks for directing me over here! I understand now that this is somewhat expected but I've noticed one thing that I'd like to bring up while aconowledging that the lift required may be disproportionate to the issue.

I've noticed these estimating respect birthdate (it won't say an event could have happened at a negative age) but it doesn't respect death date (an estimated event date can be shown as potentially happening after someone is dead). If the death date is known it would be nice for that to adjust. But like I said, it might not be worth the effort for something this minor.

**Comment by InblEric** [comment]
After reading some more and testing I realize I am probably not fully understanding what's going on here so I'm going to withdraw my previous suggestion until I better understand how it works.

Sorry about that and thanks for the info! :)
