### ISSUE TITLE
Module/PyPI name?

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#129]
Since we are cutting down issues like :christmas_tree:s and :santa: is approaching, we could think about pushing a pre-release to PyPI. In any case, I think it's time to finalize the name of the package:

- the name of the Python module (currently `gramps_webapi`)
- the name of the PyPI package (in the flask world, it is quite common to use uppercase and hyphens, i.e. `Gramps-WebAPI`)

What's you opinion? Fine like it is, or do you have a better name? Something with REST perhaps? Or something with "server"?

Once we have agreed on a name, we might also consider renaming the repository accordingly.

**Comment by cdhorn** [comment]
I'm kind of indifferent on the naming, whatever Nick and you decide on works for me. 😀

It has come along pretty nicely, it would be good to get some feedback from other Developers about it.

**Comment by cdhorn** [comment]
I wonder if we should address #90 before pushing out a pre-release.

**Comment by Nick-Hall** [comment]
The [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) section on package and modules names suggests all lowercase and discourages underscores.

Otherwise I don't mind renaming the package or repository.

**Comment by DavidMStraub** [comment]
Indeed the easiest solution would be to have only alphanumeric characters. But `grampswebapi` is quite bulky. Concerning the hpyhens & underscores: having underscores in the package name and hyphens in the PyPI project name seems to be the convention for many extension-like packages, e.g. for [Flask](https://pypi.org/search/?q=flask) or [Django](https://pypi.org/search/?q=django). I never really understood why, but suspect the reason might be the one mentioned [here](https://pybuilder.io/documentation/publishing-plugins):


> The easiest solution is to use a lowercase name without special characters. If you want the plugin name to be readable, though, you might be tempted to use underscores (the author of this document recommends namespacing with `pybuilder_*`).
[...]
> In that case, you will have to set the name of your package (for PyPI) to pybuilder-* (dashes instead of underscores).
Why this?
> - Using a project name with dashes will make your plugin installable with pip. Pip replaces underscores with dashes, so if you use underscores in the project name it will not work.
> - Having a package name with underscores is required, because using dashes in an package name is a syntax error at import.

If that problem indeed exists, I would suggest one of the following three options:

1. `grampswebapi` & `grampswebapi`
2.  `gramps_webapi` & `gramps-webapi`
3.  `gramps_web_api` & `gramps-web-api`

What is your order of preference?

**Comment by Nick-Hall** [comment]
I prefer option 2.

We could consider something like gramps-server or gramps-restful.  I'm open to alternatives if one of you has a good idea.

**Comment by cdhorn** [comment]
Yeah I like 2 as well.

**Comment by DavidMStraub** [comment]
OK then let's go for option 2, which is also good since we don't have to rename the package :wink:

**Comment by Nick-Hall** [comment]
I've changed the repository name and updated the README.
