### ISSUE TITLE
Issue authenticating with added user

### ISSUE THREAD

**Issue by windmark** [gramps-project/gramps-webapi#147]
Hey, first of all thank you for a great project exposing the Gramps data in a much better way. I'm aware that this and the gramps.js projects are still in their infancies, but I'm testing setting up for my home project.

I have wrapped the web-api in a docker image and included my Gramps data. The connection generally seem to work and with `DISABLE_AUTH=True` I can query the API endpoints without issues. 

When connecting this with Gramps.js, it seems I need to activate authentication since I'm met with a login page. Here is where I'm having issues. I have tested adding users manually with the `gramps_webapi user add admin test` and when inspecting the sqlite file I see that the user has been added with salted password. However, the `/token` endpoint is not letting me authenticate and I'm constantly met with a 401. Do you have any pointers at what I might be doing wrong?

Cheers and Merry Christmas

**Comment by DavidMStraub** [comment]
Hi @windmark, merry Christmas also to you! I've deployed my own tree just yesterday, also using Docker, and I plan to share my setup in the next few days; maybe this will help you debug. In principle, it should work the way you described it.

**Comment by windmark** [comment]
Hi @DavidMStraub I found out the error. The Swagger documentation shows the endpoints accepting `multipart/form-data` but debugging shows that flask expects `application/json`. The 401 came from the request not having the required fields (since it was empty). Might I suggest a feature of validation the request parameters and respond with a 400 (or 422) specifying the missing fields?

**Comment by DavidMStraub** [comment]
Thanks @windmark for debugging and @cdhorn for fixing! My fault since I had changed it in #83 but forgot to update the docs. Will merge tomorrow. :sleeping:

**Comment by cdhorn** [comment]
You're welcome, fix rebased.

**Comment by cdhorn** [comment]
Closing as #153 merged.
