### ISSUE TITLE
Calendar filter

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#148]
I got this idea while looking at #142. It could be something like

`/api/calendar/<year>/<month>/<day>/`

and otherwise return the same results as `/api/events/`; some wildcard character could be used to show events on a given date regardless of year.

Or maybe this should be implemented rather as a sort of filter on `/api/events/`?

**Comment by cdhorn** [comment]
Yes, excellent idea for a front page / dashboard view!

**Comment by cdhorn** [comment]
I think ?date=y/m/d with ability to use * to wildcard. 

This also has me thinking about some way to construct a ?place= filter. I think that might be useful too.

**Comment by DavidMStraub** [comment]
Implemented in #156!
