### ISSUE TITLE
Failure when processing thumbnails containing RGBA

### ISSUE THREAD

**Issue by windmark** [gramps-project/gramps-webapi#154]
The thumbnail creation in [file.py:117](https://github.com/gramps-project/gramps-webapi/blob/a8a6e5982cdf22e5aae20b31717138f62161311d/gramps_webapi/api/file.py#L117) fails with error `OSError: cannot write mode RGBA as JPEG` when media contains PNG/GIF with RGBA. This happens due to the [get_thumbnail](https://github.com/gramps-project/gramps-webapi/blob/a611816a260b58778d982e99dad79dede3db6fc8/gramps_webapi/api/image.py#L136) function defaulting to JPEG instead of reading the format dynamically.

Since we have the MIME in the `send_thumbnail` function, one suggestion is that the format is looked up dynamically and passed to `get_thumbnail`. PIL contains the Image.MIME constant, so a reverse of that could be calculated in const.py.

I have tested this locally, but haven't managed to get gramps to play along with pytest to create a proper PR yet.

**Comment by DavidMStraub** [comment]
This issue contains useful discussion: https://github.com/python-pillow/Pillow/issues/2609

I think we don't even need the MIME type, we just need to check whether the mode is `RGB` or `RGBA`; in the latter case, we can either discard the alpha channel by converting to `RGB` and return a JPEG, or return a PNG instead.
