### ISSUE TITLE
Gramps synchronization

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#163]
Eventually, especially once we implement write operations, it would be great to support two-way synchronization with Gramps desktop. I suppose it would not be too hard to implement a plugin that uses the API XML export that we already have and builds on top of the existing Import Merge Tool.

**Comment by cdhorn** [comment]
Not sure I follow your thinking and not sure how practical this is...

**Comment by Nick-Hall** [comment]
Why don't we just write directly to the database?

The only obstacle I can see at the moment is the metadata which is held in memory, but that should be easy to fix.

Then we could use [JSON patch](https://en.wikipedia.org/wiki/JSON_Patch) to modify existing objects. For example:

[{ "op": "replace", "path": "/gender", "value": "1" }]

This could be used with a PATCH request to change the gender of a person.

We could implement `person_patch` and associated database methods in core Gramps.  I have already prototyped this approach for the standard editors as a route to implement multi-user access.

**Comment by cdhorn** [comment]
Right, the GUI seeing changes shouldn't be an issue AFAIK.  But the REST API is stateless so how can it push notifications to the clients not knowing who they are?  Would clients poll for changes?

**Comment by DavidMStraub** [comment]
OK, let me elaborate what I meant. There are a couple of separate issues in my view.

### 1. Need for a Gramps &rarr; API synchronization

Let's say there is an official hosting service "GrampsCloud" and I host my tree there. I still want to keep using Gramps (as a desktop app) on my laptop and expect it to work as I'm used to when I'm sitting in an archive in a basement without wifi, or on a plane. I wouldn't want to accept, as a user, to only be able to work when I'm online. So there will be "offline" changes that need to be synced back to the "cloud". At the moment, I'm just rsync-ing my Gramps database directory to my web server, but once we allow write access to the API, there will be conflicts and there must be a way to solve them. The logic for solving these conflicts should be mostly contained in the "import merge tool", just that this would be the other way around: not merging changes from an XML file into the local tree but merging local changes into a remote tree (the API).

Note that this is quite similar (I presume) how other online services connect with their desktop counterparts, e.g. MyHeritage and Family Tree Maker (although I've never used them).

### 2. Need for an API &rarr; Gramps synchronization

This might not be necessary at the moment, but once we allow (multi-user) write access, there must be a way for a researcher to sync those changes back to their local tree; potentially with conflicts. This is exactly what the "import merge tool" does, so I think it's not difficult to implement.

### 3. Gramps using the API as a database

When I run the API locally, it shares the SQLite database with my desktop Gramps, which works in principle, but I don't think direct database access makes sense in a network context. For SQLite this doesn't work anyway, but even if someone were to use a Postgres DB, I don't think it would be sensible to make the database server accessible directly. How would one impose access rights, etc.?

Still, having Gramps directly talk to the API without a manual synchronization step is doable in principle I believe, by having a GenericDb subclass that reads and writes from the API instead of talking to a database. We could have a separate endpoint for that, accepting SQL-like payloads.

But since I think the synchronization will be necessary anyway (see above), I am not sure if this is actually worth the effort of implementing it.

### 4. Notifying Gramps of remote database changes

I am not sure, but I think currently Gramps assumes that nobody else is messing with the DB, so I don't know if it's actually possible to remain consistent when the remote DB changes while Gramps has opened it. But this is anyway only necessary in the setup in 3. above, not when using manual syncs.

### 5. Notifying app users of database changes

That the database changes while a user of a web app (or other type of app) is using the tree is a scenario that we'll anway have, regardless of whether it's due to syncing with a desktop Gramps or through direct edits with some other app. Notifying the app is indeed something we have to think about; one way would be to add a last changed timestamp to the `metadata` endpoint (which would require polling); another (more sophisticated) would be to use websockets.

**Comment by cdhorn** [comment]
Oh okay, yes I understand what you mean now and took it in the wrong context. Yes that would be a good feature and agree you would want Gramps to be able to push as well as pull changes.

**Comment by DavidMStraub** [comment]
As we're closer to having write support & collaborative editing, we have to think about a way to keep diverging local and remote databases in sync.

I'm thinking of the following procedure:

1. User opens a "synchronize with remote server" plugin in their Gramps desktop.
2. The plugin shows a username/password dialog and then fetches a full XML export from the existing `/exporters/xml/file`  endpoint
3. A modified version of the Import Merge Tool is used to display all the local vs remote (downloaded XML) differences and to choose which ones to keep
4. After consolidating all the changes, the plugin pushes a full XML of the local DB (or a JSON with necessary changes) back to a new API endpoint, where those changes are applied, after which the remote DB is exactly the same as the local DB

This would require the following:

- on the Gramps plugin side: modified import merge tool, additionally able to fetch a token and display a login form
- on the API sode: new endpoint accepting the consolidated XML or a JSON with changes (e.g. JSON patch)

What do you think?

**Comment by DavidMStraub** [comment]
... forgot to mention: *before* applying the patch in 4., we should probably make an automated backup on the server side.

**Comment by cdhorn** [comment]
Agree on automated backup. I assume there would be config option to only keep x copies around. But then having an automated backup does there not also need to be a more convenient way to restore it?

> After consolidating all the changes, the plugin pushes a full XML of the local DB (or a JSON with necessary changes) back to a new API endpoint, where those changes are applied, after which the remote DB is exactly the same as the local DB

> on the API side: new endpoint accepting the consolidated XML or a JSON with changes (e.g. JSON patch)

So I'm a little unclear here how this would work. If after a sync process it is to be _exactly_ the same as the local DB then you need to drop and recreate the database and import the XML otherwise the object change dates will continue to diverge. That may or may not be important.

**Comment by DavidMStraub** [comment]
> Agree on automated backup. I assume there would be config option to only keep x copies around. But then having an automated backup does there not also need to be a more convenient way to restore it?

True. This needs more thought.

> So I'm a little unclear here how this would work. If after a sync process it is to be exactly the same as the local DB then you need to drop and recreate the database and import the XML otherwise the object change dates will continue to diverge. That may or may not be important. But then I have not looked at the code so am I wrong about that?

Yes, either that or we have to also set the change date explicitly (which is possible).

**Comment by DavidMStraub** [comment]
I played around with a modified import merge addon but ended up starting from scratch in a more modular way (and using more of `gramps.gen.merge.diff`). The code is here until it's ready for addons-source: https://github.com/DavidMStraub/gramps-addon-webapisync

**Comment by prculley** [comment]
The object.get_schema (JSON) is used in the database differences report (and import/merge tool) to provide user readable names to the various objects.    Doug Blank created the database differences report, and I leveraged his thinking in making the import/merge.  

So I think there is a use for translated object titles.  But I can see why for general JSON export (and eventual JSON db use) we should use untranslated XML style strings.

If the JSON is not supposed to be user readable in all languages, is there a way to extend the get_schema  with translated strings a well?  Perhaps add a xmltitle tag?  Or mark these as late translate so they are not translated in the get_schema return, but can be translated for reports, and left untranslated for other purposes?

Just thoughts...

**Comment by DavidMStraub** [comment]
I will close this as the sync addon is in development and there is nothing to do in web API at this time.
