### ISSUE TITLE
Very slow relationship calculation

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#164]
Starting to work on a timeline view, I hit the issue that the person timeline endpoint is *very* slow on my tree. It takes more than 20 seconds to fetch my timeline (with default arguments), which makes it unusable in practice. I am pretty sure this is a problem within Gramps, not of our timeline code...

Most of the time is spent calculating the relationship between my 2 sisters and me, which each takes almost 10 seconds (the result being `Sister`). Something must be wrong there. Snakeviz shows that, for a single such relationship calculation, it instantiates more `Person` and `Family` objects than are present in the database.

Has anyone else encountered such problems?

**Comment by cdhorn** [comment]
Wow!  If you pull up example_gramps, is Lewis Garner (I0044) the same time wise?

**Comment by DavidMStraub** [comment]
Now, he is well below a second.

Even though I haven't investigated the code in Gramps in detail, I suspect the function derives all possible relations even if it just returns the closest one. It's quite a deep tree, up to 14 generations, over a thousand (common) ancestors.

**Comment by DavidMStraub** [comment]
Oh, I think I found the solution. If I add `calculator.set_depth(2)`, the result is near-instant...

**Comment by DavidMStraub** [comment]
When not set explicitly, the default value for the generation depth it iterates over is `behavior.generation-depth=15`, that's why it takes so long for my tree. Now the only question is what the appropriate setting for `depth` is depending on the settings. I guess `set_depth(depth=args["ancestors"])`? Or perhaps `set_depth(depth=args["ancestors"] + args["offspring"])`?

**Comment by cdhorn** [comment]
> Oh, I think I found the solution. If I add calculator.set_depth(2), the result is near-instant...

Ah, that makes sense, yeah. 

> Or perhaps set_depth(depth=args["ancestors"] + args["offspring"])?

If I had to guess without looking at code probably not sum but larger of the two.

**Comment by cdhorn** [comment]
Fixed with #166
