### ISSUE TITLE
Person timeline for people with unknown death date

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#165]
Having fun with the timeline view, I noticed that it doesn't work as (naively) expected for people that only have a birth event but no other (dated) events, but that do have offspring. I would expect to see the birth events of their children, instead there is nothing but the birth event. I could set `last=false`, but I don't want to do that in general since for people with death event using `last=true` (discarding events after death) is preferable. @cdhorn do you think we could somehow use birth + 100 years by default for people without death (or burial) event?

**Comment by cdhorn** [comment]
🤣  That is such an obvious oversight on my part!  Sorry about that.  Yes of course we ought to set some reasonable bound, I'll put a PR together later tonight if I have a chance.

**Comment by cdhorn** [comment]
Fixed with #166
