### ISSUE TITLE
Add endpoints for creating objects

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#178]
I started thinking about how to add write support to the API, starting with creating new objects (rather than modifying existing ones.

The RESTful way is obvious:

- `POST` to `/people` to create a new person
- `POST` to `/places` to create a new place
- etc.

... and the endpoints would directly map to Gramps objects.

However, this does not really work for us. Already a person has an associated `Name` in Gramps, the birth and death dates are linked as `Event`s which have `Place`s, etc., so you end up with a whole bunch of Gramps objects. Obviously, those objects are coupled, so if there is any failure during their creation, all of them or none should fail. In the Desktop app, this is handled through database transactions, but this does not really work here, as each API request is its separate database transaction. So I see two options:

1. Similar to the and `profile` option in the `GET` endpoints, use "rich" `POST` endpoints that allow to post objects that map to multiple nested objects in Gramps:

```json
{
  "name_surname": "...",
  "birth":  {
    "place": "..."
  },
"..."
}
```
But in this case handling both existing and new objects (e.g. an existing place rather than a new one for the birth place) might be tricky, and the implementation will be a lot of work since we have to define the nested structure for each object type.
2. Use objects that are closer to "raw" Gramps objects, but use an endpoint that allows to post multiple objects simultaneously, e.g. `/objects/`:
```json
[
  {
    "type": "person",
    "..."
  },
  {
    "type": "event",
    "data": {
        "type": "Birth",
    },
    "..."
  }
]
```
However in this case I am not sure how to properly handle the references between objects.

**Comment by Nick-Hall** [comment]
Yes.  Option 2 seems like the easiest to implement.

You can specify the handle in objects added to the database.  The `create_id` function can be used to generate a handle.  Look at the [`_add_base`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/db/generic.py#L1734) method.  In this way you could reference both new and existing objects.

**Comment by DavidMStraub** [comment]
I looked into this in more detail and I think indeed it's straightforward as we can directly use the Gramps internal JSON serialization for each object and generate new handles for new objects.

The only two non-trivial points I see are:

1. What if we have a new person (`handle1`) referencing a new birth event (`handle2`) and add the `Person` before the `Event`? Will it work, even though the `EventRef` points to a non-existing event?
2. Using the Gramps-internal functions for generating handles is inconvenient as you would want a front-end to be able to construct the whole JSON to be POSTed without querying the API first. Also, I am sceptical Gramps's `create_id` is safe (collision-free) enough for a multi-user server application (as opposed to a Desktop app). The solution IMO is to define new handles POSTed to the web API to be required as UUID4. Then we don't have to worry about collisions, there is a well-maintained library for every language, and it conforms with the schema `{"type": "string", "maxLength": 50}`.

**Comment by cdhorn** [comment]
Regarding UUID unsure if you were aware of https://github.com/gramps-project/gramps/pull/1005

**Comment by DavidMStraub** [comment]
Thanks for sharing, I was vaguely aware of it, but not sure if it is related; as far as I understood, it will assign UIDs to objects that can then be used to uniquely identify an object across different programs/databases. My suggestion here was simply to use the string representation of a UUID v4 (which is a random UUID) as an object handle. UUID v4 are random UUIDs (example string: `dc90d0fa-2c5c-4c12-8b41-547f16616819`) and so should be perfectly suited as handles, with negligible change of collisions.

**Comment by cdhorn** [comment]
Yes, I think Nick made a comment in that thread about how handle should probably just be a UUID but of course time to do the work to make that happen I guess is the issue. I'd have to re-read, not sure if he had a format other than v4 in mind.

**Comment by DavidMStraub** [comment]
Yeah, I see. As far as I understand the problem is *enforcing* handles to be UUIDs (which would require modifying all existing handles in a DB), while I would guess that using the string representation of a UUID4 as handle is possible anytime, as in the end it's just a string. But there might be subtleties I am missing.

**Comment by cdhorn** [comment]
The thought of every API consumer needing to generate their own object handles does not seem very clean to me design wise.

I suppose that is solved with a GET on a /handle end point anytime one is needed. 

This has me thinking back to the decision to expose the handle in the first place since Gramps ID may not be unique. Having the two identifiers instead of just one per object is really unfortunate.

**Comment by DavidMStraub** [comment]
> I suppose that is solved with a GET on a /handle end point anytime one is needed.

This is what I would really like to avoid. It's annoying to have to do a `GET` before every `POST` just for this. I also don't see the benefit, given that Gramps doesn't do a collision check or anything either, it just generates a random string.

When you're just creating a single object, there is no problem, we don't have to specify a handle at all. The issue is just when you create an object and the objects it references at the same time. This could also be done with placeholder handles with a specified format, I don't know, `__new__1`, `__new__2`, etc., which are then replaced by Gramps-generated ones in the backend, but again, I don't see a benefit w.r.t. just using a random string in the first place.

**Comment by cdhorn** [comment]
I guess it's the whole notion of insuring the handles are UUID4 if that became a requirement. The client shouldn't need to know anything about how to create a valid handle. So it either needs a way to obtain one or I like your placeholder idea and letting the API handle it on the back end.

**Comment by DavidMStraub** [comment]
> The client shouldn't need to know anything about how to create a valid handle.

Why not? Even when we use placeholders, the client has to know how to create a valid placeholder.

Making UUID4 a requirement was perhaps not a great idea, but one could make it a recommendation - in the end, it just has to be a sufficiently random string with at most 50 characters.

**Comment by cdhorn** [comment]
> Even when we use placeholders, the client has to know how to create a valid placeholder.

Yes but the structure of the place holder is defined in the API and not Gramps core. 

> in the end, it just has to be a sufficiently random string with at most 50 characters.

At the moment. But then if Nick decided to convert to UUID4 down the road and added a check to enforce it and clients were doing their own thing they would all break. Or if there was no check to enforce it but it was assumed to always be a valid UUID and that UUID was to be exchanged with external systems and it was non-compliant what would happen?

**Comment by DavidMStraub** [comment]
OK those are valid points, but if we *don't* allow passing explicit handles, that is also a limitation that needs justification. When I import a Gramps XML, it contains explicit handles for all the objects and those handles are preserved on import/export. Why shouldn't I be allowed to insert some objects via the API and choose to use some explicit handles?

Perhaps we should have both options. If it's a string, we use it directly, if it's an integer (seems more elegant than the string placeholder I suggested above), we generate a new one.

**Comment by cdhorn** [comment]
There is a difference though in that Gramps XML is handled by Gramps core.  But maybe you are right and shouldn't bother over it so much. 

I wonder what @Nick-Hall thoughts are on this.

**Comment by Nick-Hall** [comment]
Using UUID4 to generate handles is a good idea.

Converting all handles to UUID4 in the future would be tempting.
