### ISSUE TITLE
How to change the interface being listened on? 127.0.0.1

### ISSUE THREAD

**Issue by OzarkShepherd** [gramps-project/gramps-webapi#184]
I can't get Gramps.js to connect to my instance of gramps-webapi.  Ubuntu 20.04 server.  I think it is because the backend is using 127.0.0.1:5555, but since I believe the frontend is looking for 192.168.122.242:5555 in my case, it is failing.  
Here is the output of gramps-webapi.
> scott@testing:~/gramps-webapi-0.1$ python3 -m gramps_webapi --config config.cfg run --port 5555
>  * Serving Flask app 'gramps_webapi.app' (lazy loading)
> * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
> * Debug mode: off
> INFO:werkzeug: * Running on http://127.0.0.1:5555/ (Press CTRL+C to quit)

Here is the config.cfg file right now, but I have tried many variations:
>TREE="Family Tree 1"
DISABLE_AUTH=True
BASE_URL="http://192.168.122.242"
STATIC_PATH="/home/scott/Gramps.js"
CORS_ORIGINS="*"

nmap says 5555 is closed, even though I allowed it through ufw.

**Comment by DavidMStraub** [comment]
True, that should be documented.

The answer is that you have to build the frontend from source and set the `API_URL` environment variable. This is done [here](https://github.com/DavidMStraub/Gramps.js/blob/main/.github/workflows/pages.yml#L15-L21) in the Github action that deploys the frontend to Github pages, using the Gramps Web API demo on Heroku as backend.

**Comment by DavidMStraub** [comment]
Wait, I am confused. I thought you reported an issue to Gramps.js (this is what my answer was referring to). But since this is an issue for `gramps-webapi`: if you're using `python3 -m gramps_webapi`, this is anyway just for local testing as the warning says

> This is a development server. Do not use it in a production deployment.

If you want to deploy and change the port etc., use `gunicorn` with the `--bind` option.

**Comment by DavidMStraub** [comment]
I believe this can be closed here.
