### ISSUE TITLE
Place Title not displaying if Place type is Street or Number.

### ISSUE THREAD

**Issue by brucejackson** [gramps-project/gramps-webapi#190]
**Environment:**
Windows 10 PC
Gramps AIO on Windows 10 to maintain Family Tree
Docker for Windows running gramps-webapi image
Gramps.js for front end

**Issue:**
Some places do not show a Place Title in the gramps.js interface.  I have noted this behavour with Place types of Street and Number.  I am not totally clear if this is gramps.js, a gramps-webapi issue, or my data.

**Expected Behaviour**
In the snippet from Gramps.js image below, I would expect the number "56" to appear instead of the word "Place".

If in Gramps Preferences Place Formatting is set to "Street Numbering", I think I would expect the value to be "56 Shannon St", instead of "Place".

![image](https://user-images.githubusercontent.com/1219029/125518203-46fdd5bd-6c54-455d-85ee-17af7390d952.png)

**API output for 56, Shannon St, Toronto, Ontario, Canada** - 
http://localhost:5000/api/places/e8849fcdd686a3ee0877248f9cd
`{"alt_loc": [], "alt_names": [], "change": 1607438604, "citation_list": [], "code": "", "gramps_id": "P0471", "handle": "e8849fcdd686a3ee0877248f9cd", "lat": "43.6529981", "long": "-79.4246912", "media_list": [], "name": {"date": {"calendar": 0, "dateval": [0, 0, 0, false], "format": null, "modifier": 0, "newyear": 0, "quality": 0, "sortval": 0, "text": "", "year": 0}, "lang": "", "value": "56"}, "note_list": [], "place_type": "Number", "placeref_list": [{"date": {"calendar": 0, "dateval": [0, 0, 0, false], "format": null, "modifier": 0, "newyear": 0, "quality": 0, "sortval": 0, "text": "", "year": 0}, "ref": "e9e9c0fe5ba1230c73dec27a017"}], "private": false, "tag_list": [], "title": "", "urls": []}`

**Comment by DavidMStraub** [comment]
Thanks! You are right. Gramps.js only uses the `"title"` field, which is empty here. It should rather use the `"name"`. However that's a bit more tricky because there can be several names with different dates...

In any case, I think it's not a Web API issue. Unfortunately I cannot transfer it. I will link it instead.
