### ISSUE TITLE
Add endpoints for deleting objects

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#193]
This should be fairly simple. 

One questions is if we want to provide a way of undoing the delete. We cannot really do it in the backend as each request has its own database session, but we could return the JSON representation of the deleted object in the response, so a client could choose to implement an "UNDO" button that posts this object back to recreate it (which is not an "undo" from the backend perspective, but has the same effect).

A more basic question regarding the implementation of deletions in Gramps: what if I delete an event, what happens to all the event references of people and families? Looking at the DBAPI code, it looks like the `reference` table in the DB is automatically updated to remove all those references/backlinks, however the objects themselves are not updated, are they? So they still contain those "dead" references. Is there some point where Gramps cleans up those dangling references?

**Comment by Nick-Hall** [comment]
Returning a JSON representation of an undo action is a good idea.  You could also do something similar for a PATCH request.

The references are cleaned up in the front-end code.  For example, see the [DeleteEventQuery](https://github.com/gramps-project/gramps/blob/master/gramps/gui/editors/editevent.py#L329) class in the event editor.

It is probably time to move these into the backend code.  There is already a bug report [#9894](https://gramps-project.org/bugs/view.php?id=9894) - "DB-API is missing two functions".

**Comment by DavidMStraub** [comment]
> Returning a JSON representation of an undo action is a good idea. You could also do something similar for a PATCH request.

I was just thinking about a JSON representation of the object, but if we clean up references, many objects can be affected. Actually it should be simple to come up with a JSON representation of the whole `Txn` of the form

```json
[
  {
    "transaction_type": "add",
    "_class": "Person",
    "handle": "...",
    "old_data": {"<JSON representation of object>"},
    "new_data": {"<JSON representation of object>"},
  }
]
```
using `Txn.get_record`.

Undoing would be a bit more tricky for an application as it would have to dispatch multiple requests (unless we introduce a new super-endpoint that accepts arbitrary transactions, but that seems a bit unRESTful to me ...).

> The references are cleaned up in the front-end code. For example, see the DeleteEventQuery class in the event editor.

Ah, very good, that's what I was missing. We can move them to generic functions and then port them back to `gramps.gen`.
