### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#215]
We really need to improve our documentation. Following up on #202 and #186, I would like to use [this Github Action](https://github.com/marketplace/actions/deploy-mkdocs) to deploy our Markdown docs (to be extended) to Github pages.

@Nick-Hall, could you please enable Github pages in the repo settings? As far as I understand [this paragraph](https://github.com/marketplace/actions/deploy-mkdocs#building-with-github_token), you can simply set the target branch to `master` for the moment, and after the first time the action runs (I will submit a PR), switch it to the (automatically created) `gh-pages` branch.

Thanks!

**Comment by Nick-Hall** [comment]
OK.  I have enabled pages for the _/docs_ directory in the `master` branch.

Let me know when it needs changing.

**Comment by DavidMStraub** [comment]
Thanks! I pushed the workflow - can you please change the branch to `gh-pages`? :crossed_fingers:

**Comment by Nick-Hall** [comment]
Done.

**Comment by Nick-Hall** [comment]
It gives the following error:

> Your site is having problems building: No /docs folder was found to build GitHub Pages. Check the source setting for this repository. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#missing-docs-folder.

I have changed the folder to root.

**Comment by DavidMStraub** [comment]
Great, thanks! Now live at https://gramps-project.github.io/gramps-webapi/. I will add some content tonight.
