### ISSUE TITLE
http 400 error when accessing /api/translations/

### ISSUE THREAD

**Issue by brucejackson** [gramps-project/gramps-webapi#225]
Yesterday (Oct 5), I updated gramps.js and gramps-webapi/latest-devel (https://hub.docker.com/r/dmstraub/gramps-webapi/tags?page=1&ordering=last_updated) to the most recent versions.  I now get a bad request (http code 400) when accessing the following url for the translations: https://hostname/api/translations/en_GB?strings=..very long string...   The URL is 4163 bytes long.  

I can't think of anything I have changed in my environment. Any ideas on what I can try?

**Comment by DavidMStraub** [comment]
Yes, I had the same problem last week! The reason (I found out after some time) is that the length of the query string in Gramps.js crossed the threshold of 4094 characters, which is the default maximum allowed by gunicorn. You should be able to fix it like I did for the Gramps.js demo: https://github.com/DavidMStraub/Gramps.js/commit/a09e5a7a5dfeb4e733a572b464179a4ddecec95a#diff-c224df07227eab8ebf49af87a79434d70fdf42b42df4cf3004569f3aa54c2f70

I forgot to add this to the Web API docs.

**Comment by DavidMStraub** [comment]
No, actually, this isn't relevant for the docs as the docs assume you are using the docker image. So we have to change the Dockerfile. I will do it.
