### ISSUE TITLE
Gramps.js login page not showing when gramps.js deployed in webapi container

### ISSUE THREAD

**Issue by brucejackson** [gramps-project/gramps-webapi#241]
I follow the instructions to deploy gramps.js via the webapi container using the variable `GRAMPSJS_VERSION=v0.x.y` No login page was displayed.  

I need to modify the STATIC_PATH in config.cfg to 
`STATIC_PATH="/app/static/grampsjs-v0.4.1"`

I think we need a quick tweak to the docs here: https://github.com/gramps-project/gramps-webapi/blob/master/docs/Deployment.md#optional-step-use-grampsjs-web-frontend

**Comment by DavidMStraub** [comment]
No, it should work without modifying the static path. So I think something must be wrong with your environment variable.

**Comment by brucejackson** [comment]
Oh it's completely possible this is my own doing!  I am not using the nginx proxy in the documentation.  I already had virtual server at DigitalOcean so I set up my own proxy on that server.   Basically the host does a proxy_pass to my docker instance via a wireguard vpn.  

```
        location / {
            proxy_pass http://10.13.13.2:5000;
        }
```

Vivian found the same fix corrected the issue for her:  https://gramps.discourse.group/t/grampsjs-setup-cors-error-and-port-change-request/1904/27?u=ebj075

These are the contents of /app/static after I added the GRAMPJS_VERSION.   Gramps.js was downloaded to sub-directory and the index.htm has no content to return.  This is what led me to change STATIC_PATH.
```
# ls
config  db  grampsjs-v0.4.1.tar.gz  indexdir  media  src  static  thumbnail_cache  tmp  users
# ls /app/static
grampsjs-v0.4.1  index.html
# ls -l /app/static
total 4
drwxr-xr-x 4 1001  121 4096 Nov  4 12:25 grampsjs-v0.4.1
-rw-r--r-- 1 root root    0 Oct 24 20:16 index.html
#
```

I have just reverted STATIC_PATH to /app/static.   Cleared my cache and the site no longer works.  

My docker file is here: https://gist.github.com/brucejackson/344ffa6fe559b9bf32c62195cf70523e.   Please let me know if you see something that jumps out at you as an issue.

Thanks

**Comment by DavidMStraub** [comment]
Oh, now I get it. I assume you still have `STATIC_PATH` in the config file from before? With the new docker images, you shouldn't set it manually at all; it's being set correctly in the entrypoint script:
https://github.com/gramps-project/gramps-webapi/blob/master/docker-entrypoint.sh#L14

In the [deployment docs](https://gramps-project.github.io/gramps-webapi/Deployment/), `STATIC_PATH` is not mentioned (anymore).

Can you please check if removing it from the config file fixes the issue for you?

**Comment by brucejackson** [comment]
Your message popped up as I was typing this.... 😀

I just read through `docker-entrypoint.sh`
https://github.com/gramps-project/gramps-webapi/blob/master/docker-entrypoint.sh

I decided to try removing STATIC_PATH from my config.cfg.   I restarted the container.  Cleared my cache.  Loading my site and everything is good.

**Comment by brucejackson** [comment]
This can be closed.  I'll reference this ticket in the forum.  Thanks David.
