### ISSUE TITLE
Postgresql collation already exists error

### ISSUE THREAD

**Issue by Rahel-A** [gramps-project/gramps-webapi#262]
It seems that the Postgresql addon tries to create multiple collations and fails:
```
grampsweb_1  | Query is:  SELECT current_schema()
grampsweb_1  | Query is:  DROP COLLATION IF EXISTS "public"."en_GB"
grampsweb_1  | Query is:  CREATE COLLATION "en_GB"(LOCALE = 'en_GB.UTF-8')
grampsweb_1  | Query is:  SELECT current_schema()
grampsweb_1  | Query is:  DROP COLLATION IF EXISTS "public"."en_GB"
grampsweb_1  | Query is:  CREATE COLLATION "en_GB"(LOCALE = 'en_GB.UTF-8')
grampsweb_1  | Query is:  SELECT value FROM metadata WHERE setting = %s
grampsweb_1  | [2021-12-25 18:49:06 +0000] [17] [ERROR] Error handling request /api/events/?dates=*/12/25&profile=all&sort=-date&locale=en_GB
grampsweb_1  | Traceback (most recent call last):
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 136, in handle
grampsweb_1  |     self.handle_request(listener, req, client, addr)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 179, in handle_request
grampsweb_1  |     respiter = self.wsgi(environ, resp.start_response)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2091, in __call__
grampsweb_1  |     return self.wsgi_app(environ, start_response)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2076, in wsgi_app
grampsweb_1  |     response = self.handle_exception(e)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
grampsweb_1  |     response = self.full_dispatch_request()
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
grampsweb_1  |     rv = self.handle_user_exception(e)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
grampsweb_1  |     rv = self.dispatch_request()
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
grampsweb_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 45, in wrapper
grampsweb_1  |     return func(*args, **kwargs)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 84, in view
grampsweb_1  |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 158, in dispatch_request
grampsweb_1  |     return current_app.ensure_sync(meth)(*args, **kwargs)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/webargs/core.py", line 450, in wrapper
grampsweb_1  |     return func(*args, **kwargs)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/base.py", line 367, in get
grampsweb_1  |     query_method = self.db_handle.method("get_%s_handles", self.gramps_class_name)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/base.py", line 115, in db_handle
grampsweb_1  |     return get_db_handle(readonly=True)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/util.py", line 98, in get_db_handle
grampsweb_1  |     g.dbstate = dbmgr.get_db()
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 97, in get_db
grampsweb_1  |     smgr.open_activate(self.path, mode=mode, password=self.password)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbloader.py", line 112, in open_activate
grampsweb_1  |     self.read_file(filename, mode, username, password)
grampsweb_1  |   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbloader.py", line 99, in read_file
grampsweb_1  |     self.dbstate.db.load(
grampsweb_1  |   File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 594, in load
grampsweb_1  |     self._initialize(directory, username, password)
grampsweb_1  |   File "/root/.gramps/gramps51/plugins/PostgreSQL/postgresql.py", line 105, in _initialize
grampsweb_1  |     self.dbapi = Connection(**dbkwargs)
grampsweb_1  |   File "/root/.gramps/gramps51/plugins/PostgreSQL/postgresql.py", line 121, in __init__
grampsweb_1  |     self.check_collation(glocale)
grampsweb_1  |   File "/root/.gramps/gramps51/plugins/PostgreSQL/postgresql.py", line 137, in check_collation
grampsweb_1  |     self.execute('CREATE COLLATION "%s"'
grampsweb_1  |   File "/root/.gramps/gramps51/plugins/PostgreSQL/postgresql.py", line 169, in execute
grampsweb_1  |     self.__cursor.execute(sql, args, **kwargs)
grampsweb_1  | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_collation_name_enc_nsp_index"
grampsweb_1  | DETAIL:  Key (collname, collencoding, collnamespace)=(en_GB, 6, 2200) already exists.
```

This was a bit hard to figure out, I kind of got lucky to find a temporary solution. The memory footprint of running 8 gunicorn workers is a bit high on the raspberry pi 3 (~800MB), so I reduced it to 3 workers after a while, and saw that on some occasions, that I didn't get this error. So I believe one of the workers holds the lock to postgresql database, whereas the others do not...
So as a temporary patch, I can reduce the number of workers to 1 in the Dockerfile, and use all gramp.js functions without any errors:
```
- CMD gunicorn -w 8 -b 0.0.0.0:5000 gramps_webapi.wsgi:app --timeout 120 --limit-request-line 8190
+ CMD gunicorn -w 1 -b 0.0.0.0:5000 gramps_webapi.wsgi:app --timeout 120 --limit-request-line 8190
```
With this patch, I can view the map and events, I can view family tree with head_shots details fetched from the database, so on... I can't see any more problems with just 1 gunicorn worker.
What do you think @DavidMStraub? Is this a problem with how the postgresql addon can only maintain one lock with the collations, or with how gramp.js works?

**Comment by DavidMStraub** [comment]
Oh, that's interesting. Web API creates a new database connection for each request and I would have expected the workers not to interfere with each other, but looking at the Postgres Addon, it looks like it drops and recreates the collation on every database connection:
https://github.com/gramps-project/addons-source/blob/master/PostgreSQL/postgresql.py#L121-L138
That's something that doesn't make sense for a web app. Let's look into what would be the most reasonable way to change this.

**Comment by DavidMStraub** [comment]
Naively, I would say we can just remove the `DROP COLLATION IF EXISTS` and replace `CREATE COLLATION` by `CREATE COLLATION IF NOT EXISTS`. Could you try if this works for you?

**Comment by Rahel-A** [comment]
> Naively, I would say we can just remove the `DROP COLLATION IF EXISTS` and replace `CREATE COLLATION` by `CREATE COLLATION IF NOT EXISTS`. Could you try if this works for you?

That also seems to fix it. I ran with 3 workers and tried multiple refreshes whilst browsing the map on gramps.js. Didn't run into any errors.

**Comment by Nick-Hall** [comment]
Yes.  That should work.

**Comment by DavidMStraub** [comment]
Thanks, I will submit a PR to addons-source.

**Comment by DavidMStraub** [comment]
> The memory footprint of running 8 gunicorn workers is a bit high on the raspberry pi 3 (~800MB), so I reduced it to 3 workers after a while

Good point, it would make sense to make this configurable with an environement variable in the Dockerfile. Something like
```
CMD gunicorn -w ${GUNICORN_NUM_WOKERS:-8} -b 0.0.0.0:5000 gramps_webapi.wsgi:app --timeout 120 --limit-request-line 8190
```
should do the trick (but I didn't have time to test it).

**Comment by DavidMStraub** [comment]
By the way - did you use a Postgres container? I just tried it and ran into the problem that the locales don't exist in the default Postgres images (either Alpine or Debian):

```
psycopg2.errors.InvalidParameterValue: could not create locale "de_DE.UTF-8": No such file or directory
DETAIL:  The operating system could not find any locale data for the locale name "de_DE.UTF-8".
```

Did you run into this as well? I feel this is something that should be made more error proof in the Postgres Addon; it's not safe to assume that the database is running on the same system as Gramps and has the same locales installed.

**Comment by Rahel-A** [comment]
> By the way - did you use a Postgres container? I just tried it and ran into the problem that the locales don't exist in the default Postgres images (either Alpine or Debian):
> 
> ```
> psycopg2.errors.InvalidParameterValue: could not create locale "de_DE.UTF-8": No such file or directory
> DETAIL:  The operating system could not find any locale data for the locale name "de_DE.UTF-8".
> ```
> 
> Did you run into this as well? I feel this is something that should be made more error proof in the Postgres Addon; it's not safe to assume that the database is running on the same system as Gramps and has the same locales installed.

Yes I ran into this issue as well. I had to add a Dockerfile and customise the postgresql container:
```
FROM postgres:13
RUN localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8
RUN localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en
ENV LANG en_GB.utf8
```

**Comment by DavidMStraub** [comment]
Could you please comment [in this issue](https://github.com/gramps-project/addons-source/pull/523) that you have tested my modification? It might speed up merging. Once merged, I think we can close this issue and merge #260.

By the way, to allow calls with arbitrary locales, it might make sense to `apt install locales-all` in the Postgres container, do you agree?

**Comment by Rahel-A** [comment]
> should do the trick (but I didn't have time to test it).

Indeed, with this change, I can simply set this environment variable to reduce the memory footprint.

**Comment by Rahel-A** [comment]
> By the way, to allow calls with arbitrary locales, it might make sense to `apt install locales-all` in the Postgres container, do you agree?

I'm a little lost, I can't reproduce the error similar to yours. I removed the Dockerfile that I had to customise postgres container and haven't seen any locale errors... Maybe the #260 patch fixed it? I tried testing without the #260 patch as well but didn't see anything wrong.

**Comment by DavidMStraub** [comment]
The errors would appear when methods like `get_person_handles` are called with a locale different than the default  one, but I haven't invastigated yet which of the endpoints in the API are affected by it. Anyway, it's a separate problem.

**Comment by DavidMStraub** [comment]
Can be closed once https://github.com/gramps-project/addons-source/pull/523 is merged.
