### ISSUE TITLE
Heroku won't host demo anymore

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#308]
The Gramps Web demo is currently hosted on a Heroku free dyno, but it has [just been announced](https://blog.heroku.com/next-chapter) that this service will be discontinued in 2 months from now. We need to find a different solution :disappointed:

**Comment by Nick-Hall** [comment]
Perhaps we should investigate hosting the demo ourselves.

**Comment by DavidMStraub** [comment]
I was able to migrate the demo, with minimal changes, to Google Cloud. That has the benefit of still being able to deploy it from a Github workflow. I assume/hope that it will be covered by the free tier.
