### ISSUE TITLE
Remove DISABLE_AUTH

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#309]
I think we should get rid of the `DISABLE_AUTH` option. It must not be used for production anyway; originally it was meant to simplify development but I think it complicates it; developing with `DISABLE_AUTH` means we can't test functionality that depends on auth.

**Comment by DavidMStraub** [comment]
To simplify authenticated development, I added a new doc section about using HTTPie with JWT: https://gramps-project.github.io/web/dev-backend/queries/

**Comment by jeffasuk** [comment]
Hmmm... Having just started using the webapi, I really like the DISABLE_AUTH option. It allowed me to get started on what actually interested me without having to set up any auth system. If keeping it complicates development generally, then it's probably worth getting rid of. But the fact that an auth environment is needed for developing/testing "functionality that depends on auth" doesn't strike me as a reason not to have it available for other dev/test work.
(Clearly I'm new here, so my opinion should be judged in that light.)

**Comment by DavidMStraub** [comment]
What I meant is that it becomes more and more clumsy and annoying to add polyfills in the Gramps Web frontend for things that require the presence of the user system, for instance the user management component in the admin settings. In addition, we are in the process of moving more config options from the flask config file into the (user) database. We've reached a point where supporting `DISABLE_AUTH` prevents the implementation of features or selection of architectures.

What exactly makes it inconvenient for you not to use `DISABLE_AUTH` in development? Does [using httpie](https://gramps-project.github.io/web/dev-backend/queries/) for raw queries work for you?

**Comment by jeffasuk** [comment]
Thanks. That answers this: "If keeping it complicates development generally, then it's probably worth getting rid of."  Clearly that is the case, so I withdraw my comment. I'll have a look at httpie.

**Comment by jeffasuk** [comment]
(Let me know if there's somewhere more appropriate to post this; but this is the sort of difficulty I've been avoiding by using DISABLE_AUTH. It may be that there's a page somewhere explaining fully how to set up user auth, but I have found only partial information.)

I removed DISABLE_AUTH from config file. Server reported "SECRET_KEY must be specified" (fair enough!)
Added a SECRET_KEY. Now, a URL like http://localhost:5000/api/people redirects to http://localhost:5000/api/people/ (i.e. with a trailing slash, which looks like a strange change). Requesting that second URL gets a 401 UNAUTHORIZED; again, fair enough.
Next thing, tried the /api/token/ POST request. Your example from the httpie link that you sent above includes a username and password. I tried something random and got an error in sqlalchemy: unable to open database file. I tried it DISABLE_AUTH again but got the same error.
Eventually found something about using webapi to add users, here: https://gramps-project.github.io/web/Users/  Deduced the right syntax by trial and error, ending up with:
python3 -m gramps_webapi --config config user add jeff pswd (strictly a private system, of course!)
This got the "unable to open database file" error again.
Tracking this back to sqlalchemy/engine/default.py, it seems that it has made a mess of the path to the database, duplicating the path. I have USER_DB_URI="sqlite:///var/tmp/gramps/gramps-webapi-0.4.4/TESTDB/ (this is a throwaway area for my experiments). The arg to connect() in default.py is "/var/tmp/gramps/gramps-webapi-0.4.4/TESTDB/var/tmp/gramps/gramps-webapi-0.4.4/TESTDB"; i.e. with the path duplicated.
At this point I have to admit that I'm rather lost.
My working directory is /var/tmp/gramps/gramps-webapi-0.4.4 and GRAMPSHOME=`pwd`
I was working directly in the git clone area, but I have also tried a pip-installed version of gramps-webapi (also 0.4.4). Same results.

**Comment by DavidMStraub** [comment]
Hi,
the [backend development](https://gramps-project.github.io/web/dev-backend/setup/) docs have to be adapted since they currently do set `DISABLE_AUTH=True`. Without documentation, it's obviously hard. But there are just two things: the command you already figured out, and adding the database path to the config. Just use `USER_DB_URI="sqlite:///users.sqlite"`, it will be created if it doesn't exist.

> Now, a URL like http://localhost:5000/api/people redirects to http://localhost:5000/api/people/ (i.e. with a trailing slash, which looks like a strange change).

That's not a change, the correct endpoint has always been with slash - but I just realized it's incorrectly documented in the [API docs](https://gramps-project.github.io/gramps-webapi/).

**Comment by jeffasuk** [comment]
All good now. Thanks!
