### ISSUE TITLE
Place object in apispec.yml contains wrong parameter place_ref_list

### ISSUE THREAD

**Issue by bartdevriendt** [gramps-project/gramps-webapi#317]
place_ref_list should be placeref_list as defined here:

https://github.com/gramps-project/gramps/blob/master/gramps/gen/lib/place.py#L148

**Comment by DavidMStraub** [comment]
Thanks, good catch! I checked that the wrong key isn't used in Web API or Gramps.js, only in the spec.

**Comment by DavidMStraub** [comment]
Fixed by #318.
