### ISSUE TITLE
Multi-tenant server

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-webapi#328]
### Discussed in https://github.com/gramps-project/Gramps.js/discussions/152

<div type='discussions-op-text'>

<sup>Originally posted by **DallanQ** December 31, 2022</sup>
How difficult would it be to set up a multi-tenant server where people could create and invite their family to their own private trees? If that's currently difficult, is that something you'd be interested in having me work on?</div>

**Comment by DavidMStraub** [comment]
My main idea to implement a multi-tenant server would be to identify Gramps databases by their database directory path (tree names are not suited as they are not immutable and not guaranteed to be unique) and associate each user in the user database with a single tree. The structure of endpoints, etc. etc. can then stay unchanged as the right tree to use will simply be stored in the JWT along with the user ID. Since every HTTP request opens their own database connection, having multiple databases is not a problem.

The [Shared PostgreSQL addon](https://github.com/gramps-project/addons-source/pull/524) would probably be the most scalable way to host this, but it should also work with multiple SQLites.

The main challenges I see is media files, search index, caching, and configuration. Some brainstorming:

## Media files

Currently the allowed backends are local file and S3. For S3, multi tenant is easy as each tree will just use a different bucket. Local file is more tricky. I'm wondering whether we should even support it. We could also introduce a new media file backend that stores files locally, but ignores the path in the Gramps database and stores everything under the md5 hash, just like on S3.

## Search index

Probably the safest and most performant option is to have a separate directory for the search index of each tree.

## Caching

A tree ID needs to be part of the cache key so no cached queries can leak between trees. Should be easy to implement though.

## Configuration

In a multi-tenant setup, several of the config options become tree-specific, so it doesn't make sense anymore to store them in a flask config file or environment variable. We can use the database-based configuration that was introduced now for email settings and generalize it to all tree-specific config options.

**Comment by cdhorn** [comment]
I don't know enough at the present moment but still think if possible some kind of Openshift/Kubernetes solution with a front end service broker and then a persistent volume and pod per tree might make the most sense. No changes to media file, search index, or cache handling as each tree is isolated and self contained from the others. Trivial to cleanup if the user wants to delete their tree. Better manages deployment of new Gramps releases and corresponding database migrations as can be done on a rolling basis per tree as well. Plenty of horizontal scalability by adding worker nodes.

**Comment by DavidMStraub** [comment]
> I don't know enough at the present moment but still think if possible some kind of Openshift/Kubernetes solution with a front end service broker and then a persistent volume and pod per tree might make the most sense. No changes to media file, search index, or cache handling as each tree is isolated and self contained from the others. Trivial to cleanup if the user wants to delete their tree. Better manages deployment of new Gramps releases and corresponding database migrations as can be done on a rolling basis per tree as well. Plenty of horizontal scalability by adding worker nodes.

Yes, but that's already possible. In fact I don't see a big difference (or advantage) to simply using the [DigitalOcean app](https://gramps-project.github.io/web/DigitalOcean/) for individual trees.

Still, I think there is a case for running a single server hosting multiple trees and that's how I understood @DallanQ's question.

**Comment by cdhorn** [comment]
Yes that is fine if a user wants to deploy and run their own VM, and accept responsibility for properly securing it and staying current with security updates and keeping it backed up and all the rest.

Less technical users may be able to get things deployed but won't know how to do any of the later, so I agree there is a strong case for providing a hosted service.

Very interested in @DallanQ's thoughts on these things and his experience building RootsFinder and WeRelate.

**Comment by DallanQ** [comment]
Two organizations have approached me during the past few weeks asking if I could point them to an online tree manager that their users could use to create private trees and invite others to be viewers or editors. They don't want to use Ancestry due to privacy concerns. One organization involves maybe 10,000 beginning users creating small trees with stories and pictures from living memory. The other involves 100's of experienced users creating larger trees with notes and sources and inviting others to contribute. Neither organization is technical, so they'd want to allow new users to sign up and create trees without any technical support required. As you say, I've built Rootsfinder and WeRelate. Rootsfinder supports 10's of thousands of users running on a single server, but Rootsfinder is now owned by Findmypast, and WeRelate is a single tree that everyone edits, so neither is suitable.

I was very interested when I came across Gramps Web! I've known about Gramps of course, but didn't realize a web app was being built. I asked both non-profits to go through the demo tree a few days ago and tell me whether it would suit their needs. One has already gotten back to me to say that Gramps Web is very close to what they are looking for.

I know almost nothing about Gramps Web but I am interested in getting involved is if makes sense, so please read my comments with the understanding that I don't currently understand the underlying architecture but would be happy to learn. I'm going to focus my comments on scaling to 10's of thousands of users and trees. 

Database: I think a separate database per tree might work. In Rootsfinder I added tree-id as part of the key to every table, but that approach could be pretty intrusive. If you wanted to show a user which trees they had access to, you might also need a central database with a rights table (see below).

Media files: Storing the media files on S3 makes sense to me. Rather than creating separate buckets per tree, what would you think about adding the tree-id as a top-level component to the media path, before the MD5 hash? It seems like this might be easier than dealing with thousands of buckets. Is there an immutable unique tree-id?

Search index: separate directory makes sense. Could the search index also be stored on S3?

Caching: I agree that if a unique tree-id were be part of the cache key, that solves the problem.

Configuration: I hope it wouldn't be too difficult to store the tree configuration information in the tree database. You will also need a rights (ACL) table that says which users have what kind of access to which trees. It would be cached and checked in each API request. This information could also be stored in the tree database, but if you stored it in a central database it would be easy to query and show the user which trees they have access to. 

Server: Ideally we could do this with a single server (or serverless?), where either the API requests would include the tree-id as part of the request path, or else the tree-id would be in the JWT, but storing the tree-id in a header or cookie makes it harder to take advantage of HTTP caching because requests to different trees would have the same URLs.

**Comment by cdhorn** [comment]
I am glad to hear my concerns about scaling up on a single server are likely misplaced.  I can't speak to any of the rest as it is David's project and I am unsure how he sees things evolving.

**Comment by Nick-Hall** [comment]
@DavidMStraub We have some funding available for projects like this.

**Comment by DallanQ** [comment]
> I am glad to hear my concerns about scaling up on a single server are likely misplaced.
The main rootsfinder server runs in a docker container on a t2.medium machine. The server is written in golang with an nginx front-end. The redis cache and database servers run on other machines. Gedcom uploads, exports and other asynchronous functions also run on other machines that the server communicates with by putting upload/export/etc. requests onto queues. Everything runs on AWS and with auto-failover so I don't worry about machine failure.

**Comment by cdhorn** [comment]
Okay a single application server, not really a single server.  Curious, what did storage consumption look like for the database and media file storage? You also mention database servers, did you eventually have to distribute the trees across more than one?  How about backups?

**Comment by DallanQ** [comment]
Right. Media files are stored in a single s3 bucket with a key of tree-id/media-id. Database is aws rds MySQL aurora (though I’d choose Postgres now) running on a db.r3.large machine. Database storage is around 30gb (most trees are roughly 1mb), but s3 media storage is quite a bit ore than that. I never had to distribute trees, and I let aws take care of failover and backups.

**Comment by DavidMStraub** [comment]
@DallanQ thanks a lot for your input!

> Database: I think a separate database per tree might work. If you wanted to show a user which trees they had access to, you would also probably need a central database with a rights table (see below). In Rootsfinder I added tree-id as part of the key to every table, but that approach could be pretty intrusive. (If you were interested, I could work on a PR for this.)

I think this is similar to what I've done in the Shared PostgreSQL addon (see https://github.com/gramps-project/addons-source/pull/524), if I've understood correctly.

> Media files: Storing the media files on S3 makes sense to me. Rather than creating separate buckets per tree, what would you think about adding the tree-id as a top-level component to the media path, before the MD5 hash? It seems like this might be easier than dealing with thousands of buckets. Is there an immutable unique tree-id?

Right, there is no problem with doing it like that. At the moment, Gramps does not have unique tree IDs. In the shared PostgreSQL addon, there is a UUID per tree. But every database in Gramps also has a subdirectory in the Gramps database directory, so we could store a UUID there (independently of DB backend). Or we could use the name of the subdirectory, as that is unique (on the server). But a UUID would certatinly be nicer. 

> Search index: separate directory makes sense. Could the search index also be stored on S3?

The search engine uses [Whoosh](https://whoosh.readthedocs.io/en/latest/). I could be wrong, but I don't think search will be fast enough without local index.

> Configuration: I hope it wouldn't be too difficult to store the tree configuration information in the tree database. You will also need a rights (ACL) table that says which users have what kind of access to which trees. It would be cached and checked in each API request. This information could also be stored in the tree database, but if you stored it in a central database it would be easy to query and show the user which trees they have access to.

At the moment, the architecture is such that both configuration and user information are stored in two tables of a central database that is separate from the tree database.

> Server: Ideally we could do this with a single server (or serverless?), where either the API requests would include the tree-id as part of the request path, or else the tree-id would be in the JWT, but storing the tree-id in a header or cookie makes it harder to take advantage of HTTP caching because requests to different trees would have the same URLs.

I guess I don't know enough about caching here ... would having an ETag on all resources help? So requests to two different tree would have the same URLs but different ETag.

**Comment by cdhorn** [comment]
@DavidMStraub what are your thoughts around handling potentially long running tasks like imports, exports, and reports?

**Comment by DavidMStraub** [comment]
Good question. I would like to add an optional celery task broker. That's why I've already grouped the potentially long running tasks in a module called "tasks" https://github.com/gramps-project/gramps-webapi/blob/master/gramps_webapi/api/tasks.py.

I'm saying optional because I would like it to fall back to eager execution if celery is not configured, to continue allowing a single-container setup for development or demo purposes. 

I will open an issue for this.

**Comment by DallanQ** [comment]
> I think this is similar to what I've done in the Shared PostgreSQL addon (see [gramps-project/addons-source#524](https://github.com/gramps-project/addons-source/pull/524)), if I've understood correctly.

That sounds good. I'm out of town this week and next; I will look at the addon when I return.

> The search engine uses [Whoosh](https://whoosh.readthedocs.io/en/latest/). I could be wrong, but I don't think search will be fast enough without local index.

You're probably right. On AWS we may be able to store the indexes on an attached EFS drive so we wouldn't have to worry about losing them if a server went down, and we could have multiple servers if needed.

> I guess I don't know enough about caching here ... would having an ETag on all resources help? So requests to two different tree would have the same URLs but different ETag.

Yes, we could use ETags or simply turn off caching.

> Good question. I would like to add an optional celery task broker. That's why I've already grouped the potentially long running tasks in a module called "tasks" https://github.com/gramps-project/gramps-webapi/blob/master/gramps_webapi/api/tasks.py.

I like the idea of an optional celery task broker. Could we abstract it as a general queuing mechanism that could be implemented either via Celery or SQS?

**Comment by DavidMStraub** [comment]
> I like the idea of an optional celery task broker. Could we abstract it as a general queuing mechanism that could be implemented either via Celery or SQS?

I don't have experience with anything other than Celery + Redis, but apparently Celery can be used togehter with SQS if I understand correcly: 
https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/sqs.html

**Comment by DallanQ** [comment]
> I don't have experience with anything other than Celery + Redis, but apparently Celery can be used togehter with SQS if I understand correcly: https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/sqs.html

That's perfect. I was under the impression that Celery had its own back-end like RabbitMQ. But since it can sit on top of other back-ends, that makes it ideal.

**Comment by DavidMStraub** [comment]
There is one general architectural doubt I have.

I would like to assume tenant = tree and make user accounts "per tree". This would allow a clean separation of the tenants; it would mean a single server can host isolated deployments of a single tree. Requiring in addition that user names (and email adresses) must be unique *across* trees, one could use the same URL for all tenants and identify the tenant (tree) by user ID.

However, it would imply that

- a single user account cannot be used to access more than one tree
- a single email address cannot be used for two different accounts to access two different trees

The other extreme would be a setup like webtrees, where the user accounts are "per site" and each site can have multiple trees with different persmissions. This is not a multi-tenant setup, just multi-tree.

An intermediate architecture would be to have both: multiple tenants (with user accounts per tenant) as well as multiple trees per tenant. However, that's by far the most complicated option and I would really like to avoid it.

Opinions?

**Comment by DallanQ** [comment]
In my experience, the majority of online users (90%) have one tree, and the majority of trees (99%) have one user. If I understand what you're saying correctly, then the assumption that tenant = tree would work for 90% of users. I haven't set up a WebTrees server before and I'm not sure what the implications are of having a single WebTrees server with multiple trees. I don't understand the difference between WebTrees and the architecture you're trying to avoid.

**Comment by DavidMStraub** [comment]
> In my experience, the majority of online users (90%) have one tree, and the majority of trees (99%) have one user.

Thanks! That's really good to know.

> The tenant=tree option would work for option 1, but not option 2.

Exactly.

In the full-blown solution, where there are multiple tenants per server and multiple trees per user, how would a login page look like? One of the reasons I was hoping to have a simpler setup is that it would allow just having a single login page, and the tenant and tree would be uniquely identified by the user name. If we don't identify tenants by the URL, we would need an additional field for the tenant, right? And the tree would have to be selected from a list of accessible trees upon login?

Identifying the tenant by URL might be possible by serving the frontend from a directory `/tenant-slug/`, but that would require some rewriting (https://github.com/gramps-project/Gramps.js/issues/154)...

**Comment by DavidMStraub** [comment]
Still trying to wrap my head around this.

> (2) multiple professional researchers working together on multiple private trees, where different people collaborate on different trees

Would that be a single tenant, actually?

In that case, it could work like this:

1. user names (and/or email addresses, TBD) must be unique across tenants
2. tenant ID is automatically determined based on user name and/or email
3. collaboration is possible for users within one tenant
4. Users can list trees (on their tenant) they have access to

**Comment by DallanQ** [comment]
I think maybe I need to change how I use the word "tenant" here. When I've said multi-tenant, I really just mean that a single server can hold multiple trees.  It sounds like what we're saying here is that each tenant is a server or a container listening on a specific port. Is that right?

If that's the case, then yes,

1. Each tenant (server/container) would have a unique list of users. Users on the tenant would be uniquely identified by their user names or email addresses.
2. Tenant ID doesn't have to be determined, because the user logs into just one tenant.
3. Collaboration is possible for users within one tenant.
4. Users can list trees on their tenant that they have access to.

So once a user logs into their tenant, they are shown a list of trees to which they have access. And when the user selects a tree, they would access that tree with a URL that includes the selected-tree-id in the path.

In the database, there would have to be a table of (user-id, tree-id, access-level). And either (a) we'd need to add tree-id as a new column to every table, or (b) we'd need to create a separate schema per tree.

Am I understanding correctly?

**Comment by cdhorn** [comment]
> (2) multiple professional researchers working together on multiple private trees, where different people collaborate on different trees

> collaboration is possible for users within one tenant

How much of this might be concurrent activity?

Are there possibly other changes needed in the back end to help insure consistency since Gramps was originally only designed for the single user desktop use case?

**Comment by DavidMStraub** [comment]
In #343, I started implementing some changes that will make it easier to enable multi-tree/tenant support.

The part I am most unsure about is how to handle the change for S3 media files. I don't know if this is a feature that is used by many users (I use it...) but still it would be nice to at least provide a migration path.

I agree the best solution going forward is to store media files as `<tree-id>/<hash>`, whereas now they are stored just as `<hash>`. But how should users migrate their existing deployments? By a script that copies all objects and deletes the old ones? Or should we have a config parameter that enables and disables the `<tree-id>` prefix?

At some point I though we could even get away with leaving it at `<hash>` because even if MD5 is not collision-free, a preimage attack is not realistically possible. But then I realized that any user could create a media object (without uploading a file) and a given checksum, and would subsequently be able to access the file with that checksum. So any media file could be accessed with only the knowledge of the checksum. But is that actually a security issue? It's statistically impossible to brute-force guess an MD5 hash. So the only security issue would be that leaking the checksum would expose the file. But the checksum is not in any URL, so I am not sure it is a problem at all.

**Comment by DavidMStraub** [comment]
Thinking about this a bit more, I realized 

> a config parameter that enables and disables the <tree-id> prefix

is anyway needed, because for local file, *not* using a tree-dependent subdirectory is insecure and *requiring one* would not work for trying out the Web API with a local Gramps installation with existing media directory.

So I added a boolean `MEDIA_PREFIX_TREE` config option that defaults to `False`, if `True` it assumes that local media files are in a `<tree-id>` subdirectory and S3 media files are prefixed with `<tree-id>/`.

**Comment by DallanQ** [comment]
I like your idea. Is there anything (small to start) that I can do to help?

**Comment by DavidMStraub** [comment]
Thanks for asking!

I think there are three stages:

1. Disentangle all the tree-dependent data (search index, cache, media files, tokens)
2. Enable multiple trees per instance, but still tie users to a single tree
3. Allow users to access other trees

1 Is essentially done in #343, so 2 is next. I will open a couple of issues to break the work down and tag them with the [milestone](https://github.com/gramps-project/gramps-webapi/milestone/2).

**Comment by DavidMStraub** [comment]
2 is in #362.

**Comment by DavidMStraub** [comment]
Can be closed as of [v0.7.0](https://github.com/gramps-project/gramps-webapi/releases/tag/v0.7.0).
