### ISSUE TITLE
Can you clarify the MEDIA_BASE_DIR addressing scheme for S3 - want to use with alternative S3 style object storage

### ISSUE THREAD

**Issue by WGandy** [gramps-project/gramps-webapi#372]
I see the example MEDIA_BASE_DIR is 's3://my_bucket_name' which doesn't include a port number etc

I'm confused about how I should address a bucket running locally (connected by a docker network) on a Minio instance. 

For instance, if my specifics are like this:
minio container name: minio
minio port: 54321
my bucket name: my_bucket_name

Somehow this doesn't seem like it would work... 

`MEDIA_BASE_DIR: minio:54321/my_bucket_name `

**Comment by DavidMStraub** [comment]
Hi, use the `AWS_ENDPOINT_URL` variable. This should be added to the docs.

**Comment by DavidMStraub** [comment]
Fixed in https://github.com/gramps-project/web/commit/b75149cc6b1745af4f2b727c9a64661464778612.
