### ISSUE TITLE
Login auditing

### ISSUE THREAD

**Issue by kOchirasu** [gramps-project/gramps-webapi#406]
Is there a way to track logins to the website and metadata of the login (e.g. time, ip, etc)

**Comment by DavidMStraub** [comment]
Hi,

no, there isn't. You can enable debug logging to monitor the requests that are being made per endpoint, but they are not user specific.

**Comment by kOchirasu** [comment]
Any interest in having this functionality added? I can take a look at the code and see what I can do.

**Comment by DavidMStraub** [comment]
Difficult question. I feel it goes against the spirit of Gramps Web being as privacy preserving as possible.

**Comment by kOchirasu** [comment]
I intended it more as a way to audit unauthorized access. What about making it opt-in?

**Comment by DavidMStraub** [comment]
Is there a particular threat that you are thinking about, like stolen password or stolen refresh token?

**Comment by kOchirasu** [comment]
Yea either of those would be something I would like to be able to know about.

**Comment by DavidMStraub** [comment]
We could add debug logging on the token endpoint, simply using Flask's built-in logging system. Would that work? What would you like to log exactly?

**Comment by kOchirasu** [comment]
I'm thinking time+ip+user perhaps User-Agent as well.
