### ISSUE TITLE
Precommit Issues 

### ISSUE THREAD

**Issue by Samurai336** [gramps-project/gramps-webapi#413]
Hello: 

When I try to make a commit I get the following error from the precommit task 

```
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [1 lines of output]
          error in pylint setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.5.*'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
```

setup.py file has not been touched.

**Comment by DavidMStraub** [comment]
Hi,

can you please check which package raises this error? Gramps Web API does not have `>=3.5.*` in its setup.py.

(It has `>=3.5`, which is also wrong since it should be `>=3.6`, but anyway...)

**Comment by DavidMStraub** [comment]
Oh wait, I get it, it's in pylint's setup.py! That's quite funny. I think `python3 -m pip install --upgrade pylint` should fix your issue.

**Comment by Samurai336** [comment]
yes, I went looking for at setup.py in gramps and had a feeling that was not the issue. 

Currently running pylint `Version: 2.17.5` I'm not entirely sure how to tell which pre-commit step this is choking on.

**Comment by Samurai336** [comment]
found this in my cached pre-commit folder  

```
return setup(
        name="pylint",
        version=__pkginfo__["version"],
        license=__pkginfo__["license"],
        description=__pkginfo__["description"],
        long_description=long_description,
        author=__pkginfo__["author"],
        author_email=__pkginfo__["author_email"],
        url=__pkginfo__["web"],
        scripts=ensure_scripts(scripts),
        classifiers=__pkginfo__["classifiers"],
        data_files=data_files,
        ext_modules=ext_modules,
        cmdclass=cmdclass,
        extras_require=extras_require,
        test_suite="test",
        python_requires=">=3.5.*",
        setup_requires=pytest_runner,
        tests_require=["pytest"],
        **kwargs
    )
``` 
So something is generating it.

**Comment by DavidMStraub** [comment]
I assume this is fixed, or at least not a Gramps Web API bug.
