### ISSUE TITLE
Wrong formatted error messages

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-webapi#438]
After GEDCOM import I found several wrong error notes, like:
- "GOV ALTADTJN48HD" ignored, but the GEDCOM contains the custom tag _GOV
- wrong "2 DATE 1900-01-01" but the GEDCOM contains "2 DATE 01 JAN 1900"

**Comment by DavidMStraub** [comment]
Again thanks for reporting and sorry that I'm just closing this, but the Gedcom import code is handled by the Gramps project, so it should be reported there: https://www.gramps-project.org/wiki/index.php/Using_the_bug_tracker

You can also open a thread in the Gramps forum, some of the developers are there and can help with recommendations.
