### ISSUE TITLE
Sorting of "FROM" not correct in list of events

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-webapi#442]
The list of events is sorted by date, but "FROM 1 JAN 1900" is sorted to the head of the list instead just after 1899.

**Comment by DavidMStraub** [comment]
Thanks, have you checked whether this is sorted correctly in Gramps desktop when you sort the events by date in the person dialog? This would help to understand whether it's a Gramps issue or not.

**Comment by hartenthaler** [comment]
Up to now I do not use the desktop version. Maybe I should.

**Comment by DavidMStraub** [comment]
The desktop version is great :slightly_smiling_face: 

But independently from that, on which page do you see it? Is it in the "Lists/Events" table view? Or is it in the "events" tab on the person page? Or in the timeline tab?

Note, the events tab on the person page is not sorted by date - this is analogous to the behaviour in Gramps desktop. Events can be sorted by going to edit mode, highlighting an event, and then using the blue up/down buttons.

**Comment by hartenthaler** [comment]
I'm just installing Gramps Desktop.

It is the List/Events tab. It seems that FROM and TO are unrecognised and sorted as text. At least such keywords should be translated into German.

**Comment by DavidMStraub** [comment]
I'm afraid that's another GEDCOM import problem then. Gramps has powerful treatment of date spans and ranges (from/to, between/and, after, before, about, ...) and this is all properly translated, but in this case if you see a raw "FROM", it means the date was not recognized and instead stored as pure text (which also means it's not translatable).

It could be that they were open spans (i.e., with a start date and no end date) - this is something that was implemented in Gramps only recently and will be part of Gramps 5.2 to be released soon:
https://github.com/gramps-project/gramps/pull/1124

It does look like Gramps so far stored open span dates as raw date.

So, good and bad news - this is a current limitation of Gramps, but will be fixed very soon.

**Comment by hartenthaler** [comment]
Ok. I will test again when 5.2 will be released.
