### ISSUE TITLE
Synchronization between Gramps desktop and Gramps Web

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-webapi#456]
Maybe I don't understand the synchronisation concept.

1. I started with Gramps Web and imported a GEDCOM file
2. Then I installed Gramps desktop and started the application
3. The tree was automatically synchronized and was visible on the desktop application

But now there is no synchronisation anymore: changes I made in the desktop application are not visible in Gramps Web and vice versa.

**Comment by DavidMStraub** [comment]
> The tree was automatically synchronized and was visible on the desktop application

What do you mean by "automatically"? Did you install the sync addon and enter your username/password?

Docs: https://www.grampsweb.org/user-guide/sync/
