### ISSUE TITLE
Missing Dockerfile for `dmstraub/gramps:5.1.6`

### ISSUE THREAD

**Issue by paulmenzel** [gramps-project/gramps-webapi#470]
https://github.com/gramps-project/gramps-webapi/blob/0eea766aa63d13200a92ffe102b9ba6febdaffb4/Dockerfile#L1

Where can I find the Dockerfile for the reference Docker image.

**Comment by DavidMStraub** [comment]
https://github.com/DavidMStraub/gramps-docker


Could be documented better indeed.

**Comment by paulmenzel** [comment]
Awesome. Thank you for the quick response.
