### ISSUE TITLE
Refactor error handling to be more descriptive

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/gramps-webapi#93]
Refactor the error handling to provide more informative feedback to the API consumer.  At the moment we throw the obligatory status code back, but when webargs/marshmallow throw a schema validation error the information is made available to pass back to the user as to what failed. It's more polite to let them know what went wrong when possible.

This would pass a json structure back in the response with some extended information.  Something similar to this probably:
```

{
        "code": 422,
        "description": "The request was well-formed but was unable to be followed due to semantic errors.",
        "name": "Unprocessable Entity",
        "response": {
            "message": "A data validation error has occurred",
            "values": "{'rules': ['Missing data for required field.']}"
        }
    }
```

**Comment by DavidMStraub** [comment]
I implemented this recently: marshmallow now returns the error message as JSON on 422.

https://github.com/gramps-project/gramps-webapi/blob/master/gramps_webapi/api/util.py#L54
